name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: dev
          POSTGRES_PASSWORD: dev
          POSTGRES_DB: weather_postgre_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://dev:dev@localhost:5432/weather_postgre_db
      JWT_SECRET: 4e2f9b93c1d5a184f14b92c7354e27ea32596ef2c98b8d3f5d9d37b1962fe4b9
      OPENWEATHER_API_KEY: dummy
      CACHE_TTL: 1000

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma client
        run: pnpm prisma generate

      - name: Run Prisma migrations
        run: pnpm prisma migrate deploy

      - name: Run tests with Jest
        run: pnpm test -- --runInBand --detectOpenHandles
